/* Create a hacking simulator which has green background and it shows these messages with random delay of 1 to 7 seconds:-
Initializing Hacking...
Reading your files...
Password Files Detected...
Sending all passwords and personal files to server...
Cleaning up...

the three dots must blink so that it looks like a real terminal
*/